language: python
python:
  - "3.8-dev"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt codecov
# command to run tests
script:
  - flake8
  - pycodestyle .
  - pytest --cov='.' tests.py -v
  - python -m doctest README.md
after_success:
  - codecov